CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(512));
CREATE TABLE projects (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(512), description TEXT, id_category INTEGER);
CREATE TABLE blogs (id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR(512), text TEXT, dateOfCreation INTEGER, id_project INTEGER);
CREATE TABLE comments (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT, dateOfCreation INTEGER, id_project INTEGER);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, login VARCHAR(256), password VARCHAR(256), firstName VARCHAR(256), lastName VARCHAR(256), email VARCHAR(256));
CREATE TABLE active_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, id_user INTEGER, token TEXT, expireDate INTEGER);
